language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-head
script: bundle exec rspec spec
branches:
  only:
    - master
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
